title: Testing
description: Remember the old saying. Cry once when you buy it or cry every time you use it.﻿
# url: 'https://mallinanga.github.io'
# baseurl: /nanga-forestry

permalink: pretty
timezone: Europe/Athens
verbose: false
sass:
  style: compressed

collections:
  books:
    output: true
  cookies:
    output: true
  experiences:
    output: true
  locations:
    output: true
  services:
    output: true
  snippets:
    output: true

defaults:
  - scope:
        path: ""
        type: "books"
    values:
        layout: "book"
        class: "book"
        image: "/media/sample.jpg"
        categories: []
        description: ""
  - scope:
        path: ""
        type: "cookies"
    values:
        layout: "cookie"
        class: "cookie"
        description: ""
        image: "/media/sample.jpg"
  - scope:
        path: ""
        type: "experiences"
    values:
        layout: "experience"
        class: "experience"
        description: ""
        image: "http://source.unsplash.com/weekly"
  - scope:
        path: ""
        type: "locations"
    values:
        layout: "location"
        class: "location"
        description: ""
        image: "/media/sample.jpg"
        latitude: ""
        longitude: ""
  - scope:
        path: ""
        type: "services"
    values:
        layout: "service"
        class: "service"
        description: ""
        image: "/media/sample.jpg"
  - scope:
        path: ""
        type: "snippets"
    values:
        layout: "snippet"
        class: "snippet"
        description: ""
        image: "/media/sample.jpg"

prose:
  media: 'media'
  ignore:
    - /_includes
    - /_layouts
    - _config.yml

gems:
  - jekyll-menus
  - jekyll-seo-tag
  - jekyll-sitemap
